//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhonebookEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactAddress
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public int ContactDirectoryId { get; set; }
    
        public virtual ContactDirectory ContactDirectory { get; set; }
    }
}
